"""pages table

Revision ID: 28fbd4b24211
Revises: b4c74f7996de
Create Date: 2019-12-16 19:56:00.667980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28fbd4b24211'
down_revision = 'b4c74f7996de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('html', sa.Text(), nullable=True),
    sa.Column('error', sa.Integer(), nullable=True),
    sa.Column('old_rank', sa.Float(), nullable=True),
    sa.Column('web_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['web_id'], ['webs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pages')
    # ### end Alembic commands ###
