"""Add links table

Revision ID: de85d4fbd2a0
Revises: 28fbd4b24211
Create Date: 2019-12-16 20:34:51.112701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de85d4fbd2a0'
down_revision = '28fbd4b24211'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('links',
    sa.Column('from_id', sa.Integer(), nullable=False),
    sa.Column('to_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['from_id'], ['pages.id'], ),
    sa.ForeignKeyConstraint(['to_id'], ['pages.id'], ),
    sa.PrimaryKeyConstraint('from_id', 'to_id')
    )
    op.alter_column('pages', 'url',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pages', 'url',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_table('links')
    # ### end Alembic commands ###
